'''
Evaluates the model generated by running the makingAndSavingModel.py script
Manages to achieve an average accuracy of 97% with a loss <1%

Author: @asirgue
Version: 2.0 edited on 19/11 before uploading to Github
'''
import tensorflow as tf

#The following 3 lines are redundant from makingAndSavingModel.py
(x_train,y_train), (x_text, y_test) = mnist.load_data()
x_train = tf.keras.utils.normalize(x_train, axis=1)
x_test = tf.keras.utils.nomalize(x_test, axis=1)

# Loading model generated by running makingAndSavingModel.py script
model = tf.keras.models.load_model('handwritten.model')

#evaluating the model with our testing data
loss,accuracy = model.evaluate(x_test,y_test)

#Reminder: we want minimal loss and high accuracy
print(loss)
print(accuracy)
